//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ClassLevelTable struct {
	ID                  int32 `sql:"primary_key"`
	Name                string
	Level               *string
	BaseAttackBonus     *string
	FortSave            *string
	RefSave             *string
	WillSave            *string
	CasterLevel         *string
	PointsPerDay        *string
	AcBonus             *string
	FlurryOfBlows       *string
	BonusSpells         *string
	PowersKnown         *string
	UnarmoredSpeedBonus *string
	UnarmedDamage       *string
	PowerLevel          *string
	Special             *string
	Slots0              *string
	Slots1              *string
	Slots2              *string
	Slots3              *string
	Slots4              *string
	Slots5              *string
	Slots6              *string
	Slots7              *string
	Slots8              *string
	Slots9              *string
	SpellsKnown0        *string
	SpellsKnown1        *string
	SpellsKnown2        *string
	SpellsKnown3        *string
	SpellsKnown4        *string
	SpellsKnown5        *string
	SpellsKnown6        *string
	SpellsKnown7        *string
	SpellsKnown8        *string
	SpellsKnown9        *string
	Reference           *string
}
