//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Class struct {
	ID                   int32 `sql:"primary_key"`
	Name                 string
	Type                 *string
	Alignment            *string
	HitDie               *string
	ClassSkills          *string
	SkillPoints          *string
	SkillPointsAbility   *string
	SpellStat            *string
	Proficiencies        *string
	SpellType            *string
	EpicFeatBaseLevel    *string
	EpicFeatInterval     *string
	EpicFeatList         *string
	EpicFullText         *string
	ReqRace              *string
	ReqWeaponProficiency *string
	ReqBaseAttackBonus   *string
	ReqSkill             *string
	ReqFeat              *string
	ReqSpells            *string
	ReqLanguages         *string
	ReqPsionics          *string
	ReqEpicFeat          *string
	ReqSpecial           *string
	SpellList1           *string
	SpellList2           *string
	SpellList3           *string
	SpellList4           *string
	SpellList5           *string
	FullText             *string
	Reference            *string
}
