//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Feat struct {
	ID           int32 `sql:"primary_key"`
	Name         string
	Type         *string
	Multiple     *string
	Stack        *string
	Choice       *string
	Prerequisite *string
	Benefit      *string
	Normal       *string
	Special      *string
	FullText     *string
	Reference    *string
}
