//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Item struct {
	ID              int32 `sql:"primary_key"`
	Name            string
	Category        *string
	Subcategory     *string
	SpecialAbility  *string
	Aura            *string
	CasterLevel     *string
	Price           *string
	ManifesterLevel *string
	Prereq          *string
	Cost            *string
	Weight          *string
	FullText        *string
	Reference       *string
}
