//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Power struct {
	ID               int32 `sql:"primary_key"`
	Name             string
	Discipline       *string
	Subdiscipline    *string
	Descriptor       *string
	Level            *string
	Display          *string
	ManifestingTime  *string
	Range            *string
	Target           *string
	Area             *string
	Effect           *string
	Duration         *string
	SavingThrow      *string
	PowerPoints      *string
	PowerResistance  *string
	ShortDescription *string
	XpCost           *string
	Description      *string
	Augment          *string
	FullText         *string
	Reference        *string
}
