//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Skill struct {
	ID          int32 `sql:"primary_key"`
	Name        string
	Subtype     *string
	KeyAbility  *string
	Psionic     *string
	Trained     *string
	ArmorCheck  *string
	Description *string
	SkillCheck  *string
	Action      *string
	TryAgain    *string
	Special     *string
	Restriction *string
	Synergy     *string
	EpicUse     *string
	Untrained   *string
	FullText    *string
	Reference   *string
}
