//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Class = Class.FromSchema(schema)
	ClassLevelTable = ClassLevelTable.FromSchema(schema)
	Domain = Domain.FromSchema(schema)
	Equipment = Equipment.FromSchema(schema)
	Feat = Feat.FromSchema(schema)
	Item = Item.FromSchema(schema)
	Monster = Monster.FromSchema(schema)
	Power = Power.FromSchema(schema)
	Skill = Skill.FromSchema(schema)
	Spell = Spell.FromSchema(schema)
}
